config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'
  
  resources :receipts do 
    resources :comments, only: [:create]
  end
  
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :ingredients, except: [:destroy]
  mount ActionCable.server => '/cable'
  get '/chat', to: 'chatrooms#show'
  
  resources :messages, only: [:create]
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 5, maximum: 500 } 
  
  belongs_to :chef
  validates :chef_id, presence: true
  default_scope -> { order(updated_at: :desc)}
  has_many :receipt_ingredients
  has_many :ingredients, through: :receipt_ingredients
  has_many :comments, dependent: :destroy
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy] 
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def index
    @receipts = Receipt.paginate(page: params[:page], per_page: 5)
  end
  
  def show
    @comment = Comment.new
    @comments = @receipt.comments.paginate(page: params[:page], per_page: 5)
  end
  
  def new
    @receipt = Receipt.new
  end
  
  def create
    @receipt = Receipt.new(receipt_params)
    @receipt.chef = current_chef
    if @receipt.save
      flash[:success] = "Receipt was created successfuly!"
      redirect_to receipt_path(@receipt)
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @receipt.update(receipt_params)
      flash[:success] = "Receipt was updated successfuly!"
      redirect_to receipt_path(@receipt)
    else 
      render 'edit'
    end
  end
  
  def destroy
    Receipt.find(params[:id]).destroy
    flash[:success] = "Receipt deleted successfuly"
    redirect_to receipts_path
  end
  
  private
  
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end
  
    def receipt_params
      params.require(:receipt).permit(:name, :description, ingredient_ids: [])
    end
    
    def require_same_user
      if current_chef != @receipt.chef and !current_chef.admin?
        flash[:danger] = "You can only edit or delete your own receipts"
        redirect_to receipts_path
      end
    end
end

app/views/receipts/_form.html.erb
<%= render 'shared/errors', obj: @receipt %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@receipt, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of receipt", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create receipt" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
              <% cb.label(class: "checkbox-inline input_checkbox") { cb.check_box(class: "checkbox") + cb.text} %>
            <% end %>
            
          </div>

        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to receipts listing", receipts_path %> ]
    </div>
  </div>
</div>

app/views/receipts/_receipt.html.erb
<% obj.each do |receipt| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= gravatar_for(receipt.chef, size: 120) %>
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to receipt.name, receipt_path(receipt) %></h4>
      <p><%= truncate(receipt.description, length: 150) %></p>
      <% if receipt.ingredients.any? %>
        <p>Ingredients: <%= render receipt.ingredients %></p>
      <% end %>
      <p>
        <span class="quiet"><small>Created <%= time_ago_in_words(receipt.created_at) %> ago <%= receipt.chef.chefname.capitalize %>
                                                          | <%= pluralize(receipt.comments.count, 'Comment') %></small></span>
      </p>
      <% if logged_in? && (current_chef ==  receipt.chef || current_chef.admin?) %>
        <div class="receipt-actions">
          <%= link_to "Edit this receipt", edit_receipt_path(receipt), class: "btn btn-xs btn-warning" %>
          <%= link_to "Delete this receipt", receipt_path(receipt), method: :delete,
                                           data: { confirm: "Are you sure you want to delete this receipt?"},
                                           class: "btn btn-xs btn-danger" %>
          
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<%= render 'shared/page_title', title: "edit an existing receipt" %> 
<%= render 'form' %>

app/views/receipts/index.html.erb
<%= render 'shared/page_title', title: "showing all receipts" %>


<div align="center">
  <%= will_paginate %>
</div>

<%= render 'receipt', obj: @receipts %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/receipts/new.html.erb
<%= render 'shared/page_title', title: "create a new receipt" %> 
<%= render 'form' %>

app/views/receipts/show.html.erb
<%= render 'shared/page_title', title: @receipt.name %>

<div class="row">
  <div class="well col-md-8 col-md-offset-2">
    <h4 class="center description"><strong>Steps: </strong></h4>
    <hr/>
    <% if @receipt.ingredients.any? %>
      <p>Ingredients: <%= render @receipt.ingredients %></p>
    <% end %>
    <%= simple_format(@receipt.description) %>
    <hr/>
    <div class="pull-right">
        <p class="center"></p>
          <em></em>Created by:</em>
        </p>
        <p class="center">
          <%= link_to gravatar_for(@receipt.chef), chef_path(@receipt.chef) %>
          </p>
          <p class="center">
            <small><%= @receipt.chef.chefname.capitalize %> </small>
            <div class="pull-right"><%= time_ago_in_words(@receipt.created_at) %> ago</div>
          </p>
    </div>
    <div class= "receipt-actions">
      <% if logged_in? && (current_chef == @receipt.chef || current_chef.admin?) %>
        <%= link_to "Edit this receipt", edit_receipt_path(@receipt), class: "btn btn-xs btn-warning" %>
        <%= link_to "Delete this receipt", receipt_path(@receipt), method: :delete,
                                           data: { confirm: "Are you sure you want to delete this receipt?"},
                                           class: "btn btn-xs btn-danger" %>
      <% end %>
     <%= link_to "Return to receipts listing", receipts_path, class: "btn btn-xs btn-primary" %>

    </div>
  </div>
</div>  

<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
      <%= form_for([@receipt, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-md-2">
            <%= f.label :description, "Comment" %>
          </div>
          <div class="col-md-8">
            <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-10">
            <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
          </div>
        </div>
      <% end %>
      <hr/>
    </div>
  </div>
<% end %>

<% if @receipt.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Prior Comments: </h3>
      <div id="messages">
        <%= render partial: 'comments/comments', object: @comments %>
      </div>
    </div>
  </div>
  <% else %>
  <div class= "row">
    <div class="col-md-8 col-md-offset-2">
      <h3>No Comments Yet!</h3>
    </div>
  </div>
<% end %>